src/objects/cart__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cost__c</fullName>
        <label>cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>cart</label>
    <nameField>
        <label>cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpenCheckout.cls
public class OpenCheckout {
String ctyname;      
    
    public  List<cart__C> getchecker(){
      List<cart__C> splist =[select name,cost__c,quantity__c,total__c from cart__C];
      //  List<SelectOption> splist = new List<SelectOption>();

        
//	List<CartPojo> cp=new list<CartPojo>();
			     
             return splist;
    }
    
    public void delCart(){
          
		      ctyname=apexpages.currentPage().getParameters().get('ctyname');
        cart__c cart = [SELECT Id, Name,quantity__c,total__c FROM cart__c

                         WHERE Name=:ctyname limit 1];
        
        if(cart.quantity__c==1){
delete cart;
    }
        else{
            try {  
          
    cart__c cartToUpdate=  [SELECT name,quantity__c,total__c FROM cart__c WHERE Name=:ctyname LIMIT 1];

    cartToUpdate.Quantity__c = cartToUpdate.Quantity__c-1;

    update cartToUpdate;
} catch(DmlException e) {
    System.debug('An unexpected error has occurred: ' + e.getMessage());
}


        }
    
}
}