src/objects/cart__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>cost__c</fullName>
        <label>cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>cart</label>
    <nameField>
        <label>cart Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ShoppingProduct__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Appliances</fullName>
                </value>
                <value>
                    <fullName>Buildings</fullName>
                </value>
                <value>
                    <fullName>Clothing</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
                <value>
                    <fullName>Food</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>ShoppingProduct</label>
    <nameField>
        <label>ShoppingProduct Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ShoppingProducts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PickListFetcher.cls
public class PickListFetcher {

 	public  static String data1{get;set;}
    public  String ctyname;//{get;set;}
    public  integer cost;//{get;set;}
	String  value;
    String name;
    public PickListFetcher(){
    	system.debug('constructor called plf');
        value = apexpages.currentPage().getParameters().get('id');
    }   

 	public  List<ShoppingProduct__c>  getShowProducts(){
    	list<ShoppingProduct__c> splist =[select name,cost__c,category__c from ShoppingProduct__c where category__c=:value];
        return splist;
    }
  	
    public pageReference opencheckoutPage() {
    	pageReference pg = new pageReference('/apex/checkout');
        pg.setRedirect(true);
        return pg;
    }  
    
    public  Void insertData(){
        

                ctyname= apexpages.currentPage().getParameters().get('ctyname');
        system.debug(ctyname);
        list<cart__c> splist =[select name,quantity__c from cart__c where name=:ctyname];
        system.debug('@@@@'+splist +'   '+ ctyname);
      
        if(splist.size()==0){
            system.debug('in if');
        Integer cos=Integer.valueOf(apexpages.currentPage().getParameters().get('cost'));
        insert (new cart__C(name=ctyname,cost__c=cos,Quantity__c=1));
        }
        else
        {
             try {      
    cart__c cartToUpdate=  [SELECT name,quantity__c FROM cart__c WHERE Name=:ctyname LIMIT 1];

    cartToUpdate.Quantity__c = cartToUpdate.Quantity__c+1;

    update cartToUpdate;
} catch(DmlException e) {
    System.debug('An unexpected error has occurred: ' + e.getMessage());
}


        }
    }
}