src/objects/Employee_login__c.object
<CustomObject>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>25</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <label>Employee login</label>
    <nameField>
        <label>Employee login Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employee logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeLogin.cls
public class EmployeeLogin {
    
    @Auraenabled
    public static String authenticateDetails(String empID,String password){
        
        try{
            Employee_login__c loginDetails = [Select id,password__c,name from Employee_login__c where name=:empID];
            
            if(empID!=null && loginDetails!=null){
                if(loginDetails.password__c == password && loginDetails.name == empID)
                {
                    return empID;
                }            
            }
        } catch (Exception e){
            return null;
        }
        return null;
    }
    
}